# 例外処理

## try catch構文

* この機能は**例外処理**と呼ばれる
* エラーが発生すると現在の正常な処理を中断して別の処理を実行する

```php
try {
    throw new 例外クラス('エラーが発生しました');
} catch (例外クラス 変数) {
    echo 変数->メソッド();
}
```

* `try`ブロックでエラーが発生すると、例外(クラス)をthrow(投げる)する
* `catch`ブロックは投げられた例外を捕捉する
    * ここでthrowできるものは`Exception`クラスかそのサブクラスのオブジェクト
* この変数を利用してcatchブロック内でエラー表示などの処理を実行する

## エラーハンドリング

* プログラムの正常な状態に復帰する処理
    * エラーを検知した際に動作
* **エラーハンドラ**
    * 担当する機能


